# Generated by Django 5.0.3 on 2024-03-22 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Importer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EventEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('tagline', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='XpathImporter',
            fields=[
                ('importer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aggregator.importer')),
                ('events_elements_xpath', models.CharField(max_length=255)),
                ('date_xpath', models.CharField(max_length=255)),
                ('time_xpath', models.CharField(max_length=255)),
                ('location_xpath', models.CharField(max_length=255)),
                ('title_xpath', models.CharField(max_length=255)),
                ('tagline_xpath', models.CharField(max_length=255)),
                ('link_xpath', models.CharField(max_length=255)),
                ('cost_xpath', models.CharField(max_length=255)),
            ],
            bases=('aggregator.importer',),
        ),
    ]
