# Generated by Django 5.0.3 on 2024-03-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpathimporter',
            name='site_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xpathimporter',
            name='url',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
