# Generated by Django 5.0.3 on 2024-04-02 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0002_xpathimporter_site_name_xpathimporter_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpathimporter',
            name='date_format',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='xpathimporter',
            name='time_format',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='xpathimporter',
            name='cost_xpath',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='xpathimporter',
            name='link_xpath',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='xpathimporter',
            name='location_xpath',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='xpathimporter',
            name='tagline_xpath',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='xpathimporter',
            name='time_xpath',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
