# Generated by Django 5.0.3 on 2024-04-02 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0004_alter_evententry_link_alter_evententry_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evententry',
            name='cost',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
