# Generated by Django 5.0.3 on 2024-06-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0005_alter_evententry_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='evententry',
            name='unique_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='xpathimporter',
            name='unique_id_xpath',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
