# Generated by Django 5.0.3 on 2024-06-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0006_evententry_unique_id_xpathimporter_unique_id_xpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpathimporter',
            name='unique_id_attr',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
